controller:
  contextToken:
    profile: transaction-token
    issuer: http://kontxt-tts.orka-system.svc.cluster.local:8080
    audience: orka
    headers: Txn-Token
    authzMode: enforce
    tts:
      endpoint: http://kontxt-tts.orka-system.svc.cluster.local:8080/token_endpoint
      audience: orka
      tokenSource: incoming
      childScope: orka:tasks:get orka:tools:http
      outboundScope: orka:tools:http
